### PR TITLE
estimate_gas: do not serialize null block number

### LINKED ISSUE #290: Estimate Gas Not Working With Geth
`Eth::estimate_gas` does not seem to work when connected to a geth node. From what I can gather this is because ethereum/go-ethereum#2586 where geth does not implement the documented Web3 specification for `eth_estimateGas`.

According to the [specification](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_estimategas), `eth_estimateGas` expects the same parameters as `eth_call`, that is (in `rust-web3` terms) a  `CallRequest` and a `BlockNumber`. However, geth seems to only accept a `CallRequest` and with fail when a `BlockNumber` is specified.

This is a problem when using any geth node (such as when using Infura). The following code illustrates this problem:

```rust
use futures::future::Future;
use serde_json::json;
use std::env;
use web3::api::Web3;
use web3::transports::Http;
use web3::types::CallRequest;
use web3::Transport;

fn main() {
    let (eloop, http) = {
        let project_id = env::var("INFURA_PROJECT_ID").unwrap();
        Http::new(&format!("https://rinkeby.infura.io/v3/{}", project_id)).unwrap()
    };
    eloop.into_remote();
    let web3 = Web3::new(http.clone());

    println!(
        "Client version: {:?}",
        web3.web3().client_version().wait().unwrap()
    ); // Client version: "Geth/v1.9.7-omnibus-cc8122b7-20191122/linux-amd64/go1.13.4"

    let gas = web3
        .eth()
        .estimate_gas(
            CallRequest {
                from: None,
                to: "000102030405060708090a0b0c0d0e0f10111213".parse().unwrap(),
                gas: None,
                gas_price: None,
                value: None,
                data: None,
            },
            None,
        )
        .wait();
    println!("{:?}", gas); // Err("too many arguments, want at most 1")

    let gas = http
        .execute(
            "eth_estimateGas",
            vec![json!({
                "to": "0x000102030405060708090a0b0c0d0e0f10111213",
            })],
        )
        .wait();
    println!("{:?}", gas); // Ok("0x5208") == 21000 == BASE_GAS_PRICE (as expected)
}
```

I suggest doing as `web3.py` does (ethereum/web3.py#1046) and only send the `CallRequest` parameter on a `eth_estimateGas` request when the specified `BlockNumber` is `None`. This works with other nodes such as parity and development nodes such as Ganache so it shouldn't impact `rust-web3` users while allowing them to successfully call `eth_estimateGas` when connected to geth nodes.

This feels icky as it requires `rust-web3` to work around an issue that is arguably a geth bug, but seeing as ethereum/go-ethereum#2586 has been open since 2016 I think it is a worthwhile workaround (especially since geth is widely used, and used with Infura).

### PR DESCRIPTION
**Pull request by vorot93**
Do not serialise second argument (block number) if it's null. This is a workaround for ethereum/go-ethereum#2586. Fixes #290.

### CODE REVIEW

File: src/api/eth.rs [hunk 1]
```diff
@@ -72,9 +72,16 @@ impl<T: Transport> Eth<T> {
     /// Call a contract without changing the state of the blockchain to estimate gas usage.
     pub fn estimate_gas(&self, req: CallRequest, block: Option<BlockNumber>) -> CallFuture<U256, T::Out> {
         let req = helpers::serialize(&req);
-        let block = helpers::serialize(&block.unwrap_or(BlockNumber::Latest));
 
-        CallFuture::new(self.transport.execute("eth_estimateGas", vec![req, block]))
+        let args = {
```
Comment (tomusdrw) [inline src/api/eth.rs]: Minor style nitpick:
```rust
let args = match block {
  Some(block) => vec![req, helpers::serialize(&block)],
  None => vec![req],
};
```
would be my preferred style.

File: src/contract/mod.rs [hunk 2]
```diff
@@ -362,7 +362,7 @@ mod tests {
         };
 
         // then
-        transport.assert_request("eth_estimateGas", &["{\"data\":\"0x06fdde03\",\"from\":\"0x0000000000000000000000000000000000000005\",\"to\":\"0x0000000000000000000000000000000000000001\"}".into(), "\"latest\"".into()]);
+        transport.assert_request("eth_estimateGas", &["{\"data\":\"0x06fdde03\",\"from\":\"0x0000000000000000000000000000000000000005\",\"to\":\"0x0000000000000000000000000000000000000001\"}".into()]);
```
Comment (tomusdrw) [inline src/contract/mod.rs]: Can you add a test with the block number set as well?

Comment (vorot93) [reply src/contract/mod.rs]: Added in `Eth` transport tests.

File: src/api/eth.rs (hunk 1 above)
Comment (vorot93) [reply src/api/eth.rs]: Fixed
