### PR TITLE
Fix build with OpenSSL 1.1.1

### LINKED ISSUE #162: openssl 1.1.1 - can't build  `openssl v0.9.24`
See https://github.com/sfackler/rust-openssl/issues/994 for details

All crates that are using `openssl v.0.9.24` need be bumped/patched such as:
* `jsonrpc-core`
* `hyper`
* `hyper-tls`
* `native-tls`
* `websocket`

### PR DESCRIPTION
**Pull request by InsidiousMind**
Update hyper to 0.12
Update hyper-tls to 0.3
update websocket to 0.21
Update http.rs to new hyper 0.12 API
bump version

Fixes #162 

This fix means upgrading to hyper 0.12 to support OpenSSL 1.1.1. This works out OK, but the largest change to take note of would probably be the removal of typed-headers in 0.12.

### CODE REVIEW

File: src/transports/http.rs [hunk 1]
```diff
@@ -119,15 +126,17 @@ impl Http {
...
             let user = url.username();
 
             if user.len() > 0 {
-                Some(hyper::header::Basic {
-                    username: user.into(),
-                    password: url.password().map(Into::into),
-                })
+                let auth = match url.password() {
+                    Some(pass) => format!("{}:{}", user, pass),
+                    None => format!("{}:", user)
```
Comment (tomusdrw) [inline src/transports/http.rs]: you sure we need the trailing `:`? Maybe let's encode only the username.

File: src/transports/http.rs [hunk 2]
```diff
@@ -147,24 +156,21 @@ impl Http {
...
         }
-        // Send basic auth header
         if let Some(ref basic_auth) = self.basic_auth {
-            req.headers_mut()
-                .set(hyper::header::Authorization(basic_auth.clone()));
+            req.headers_mut().insert(hyper::header::AUTHORIZATION, basic_auth.clone());
         }
-        req.set_body(request);
-
+        // Send basic auth header
```
Comment (tomusdrw) [inline src/transports/http.rs]: The comment should be above `if` I suppose :)

File: src/transports/http.rs (hunk 1 above)
Comment (InsidiousMind) [reply src/transports/http.rs]: I was conflicted on this myself, since the HTTP Basic Auth RFC does not specify exactly what to do with an empty password, just that the format must be 'Basic username:password', with user:pass part encoded in Base64. I am not well-versed on HTTP spec, though, so I may be wrong on this, but figured it would be safest to do 'user:'

https://tools.ietf.org/html/rfc7617#section-2

My conclusion was no password just counts as an 'empty' password so it would be encoded as 'Basic username:'

Comment (tomusdrw) [reply src/transports/http.rs]: Ok, makes sense!
