### PR TITLE
Decoding FixedBytes.

### LINKED ISSUE #50: I can not receive the values of "byte[64][]" returned by the contract.
It is the continuation of #47.
Thank you for the correspondence of #47.

When I tried it with the latest source, I can compile it, but I get an InvalidOutputType error.
I tried several while changing the type, but it did not work.

contract interface:
```
function getValues() public constant returns (uint[], byte[64][], address[])
```

rust source:
```
let result = contract.query("getValues", (), None, Options::default());
let a = result.wait();
match a {
    Ok(_) => {
        let (v1, v2, v3): (Vec<U256>, Vec<Vec<u8>>, Vec<Address>) = a.unwrap();
        println!("{:?} {:?} {:?}", v1, v2, v3);
    }
    Err(e) => println!("{:?}", e),
};
```

Try 1:
```
let (v1, v2, v3): (Vec<U256>, Vec<Vec<u8>>, Vec<Address>) = a.unwrap();
```
```
InvalidOutputType("Expected `bytes`, got FixedArray([FixedBytes([206]), FixedBytes([72]), FixedBytes([241]), FixedBytes([97]), FixedBytes([207]), FixedBytes([128]), FixedBytes([204]), FixedBytes([70]), FixedBytes([118]), FixedBytes([206]), FixedBytes([78]), FixedBytes([231]), FixedBytes([240]), FixedBytes([253]), FixedBytes([6]), FixedBytes([167]), FixedBytes([83]), FixedBytes([97]), FixedBytes([140]), FixedBytes([94]), FixedBytes([69]), FixedBytes([6]), FixedBytes([147]), FixedBytes([168]), FixedBytes([87]), FixedBytes([143]), FixedBytes([48]), FixedBytes([134]), FixedBytes([203]), FixedBytes([234]), FixedBytes([137]), FixedBytes([164]), FixedBytes([184]), FixedBytes([9]), FixedBytes([192]), FixedBytes([144]), FixedBytes([96]), FixedBytes([23]), FixedBytes([52]), FixedBytes([205]), FixedBytes([78]), FixedBytes([122]), FixedBytes([134]), FixedBytes([64]), FixedBytes([80]), FixedBytes([76]), FixedBytes([37]), FixedBytes([106]), FixedBytes([206]), FixedBytes([151]), FixedBytes([106]), FixedBytes([107]), FixedBytes([192]), FixedBytes([75]), FixedBytes([183]), FixedBytes([11]), FixedBytes([217]), FixedBytes([134]), FixedBytes([250]), FixedBytes([98]), FixedBytes([112]), FixedBytes([183]), FixedBytes([106]), FixedBytes([225])])")
```

Try 2:
```
let (v1, v2, v3): (Vec<U256>, Vec<Vec<H256>>, Vec<Address>) = a.unwrap();
```
```
InvalidOutputType("Expected `H256`, got [206]")
```

Try 3:
```
let (v1, v2, v3): (Vec<U256>, Vec<Vec<[H256; 1]>>, Vec<Address>) = a.unwrap();
```
```
InvalidOutputType("Expected `FixedArray(1)`, got FixedBytes([206])")
```

How can I receive the values?
Thank you.

### PR DESCRIPTION
**Pull request by tomusdrw**
Fixes #50

Seems that also `FixedBytes` deserialization was missing.

### CODE REVIEW

File: src/contract/tokens.rs [hunk 1]
```diff
@@ -207,8 +208,31 @@ impl<T: Tokenizable> Tokenizable for Vec<T> {
...
+        match token {
+          Token::FixedBytes(bytes) => {
+            if bytes.len() != $num {
+              return Err(Error::InvalidOutputType(format!("Expected `FixedBytes({})`, got FixedBytes({})", $num, bytes.len())));
+            }
+
+            let mut arr = [0; $num];
+            for i in 0..$num {
+              arr[i] = bytes[i];
+            }
```
Comment (debris) [inline src/contract/tokens.rs]: maybe `copy_from_slice`?

Comment (tomusdrw) [inline src/contract/tokens.rs]: Good point, thanks!
